services:
  pgdatabase_hw:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}    
      - POSTGRES_PASSWORD=${POSTGRES_PW}                  
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin_hw:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "8080:80"
